version: '3'

networks:
  docker-local-network:
    driver: bridge
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - docker-local-network
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.5.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - docker-local-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601